from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    ListFlowable,
    ListItem,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch


def generate_architecture_pdf(
    data,
    filename="architecture_report.pdf",
):
    """
    Generates polished executive PDF report
    for SystemForge AI
    """

    styles = getSampleStyleSheet()

    # -----------------------------
    # Custom Styles
    # -----------------------------

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        leading=30,
        spaceAfter=20,
    )

    section_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading2"],
        fontSize=16,
        leading=22,
        spaceAfter=10,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=11,
        leading=17,
        spaceAfter=6,
    )

    small_style = ParagraphStyle(
        "Small",
        parent=styles["BodyText"],
        fontSize=10,
        leading=15,
        spaceAfter=4,
    )

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
    )

    content = []

    # =====================================================
    # COVER PAGE
    # =====================================================

    content.append(
        Paragraph(
            "SYSTEMFORGE AI",
            title_style,
        )
    )

    content.append(
        Paragraph(
            "Production Workflow Redesign Report",
            section_style,
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Executive Architecture Summary for AI-Native Deployment",
            body_style,
        )
    )

    content.append(
        Paragraph(
            "Generated by SystemForge Architecture Intelligence Engine",
            small_style,
        )
    )

    content.append(Spacer(1, 30))

    metrics = data.get("finalMetrics", {})

    deployment_readiness = metrics.get(
        "deploymentReadiness",
        "N/A",
    )

    automation_potential = metrics.get(
        "automationPotential",
        "N/A",
    )

    architecture_confidence = metrics.get(
        "architectureConfidence",
        "High",
    )

    content.append(
        Paragraph(
            f"<b>Deployment Readiness:</b> {deployment_readiness}",
            body_style,
        )
    )

    content.append(
        Paragraph(
            f"<b>Automation Potential:</b> {automation_potential}",
            body_style,
        )
    )

    content.append(
        Paragraph(
            f"<b>Architecture Confidence:</b> {architecture_confidence}",
            body_style,
        )
    )

    content.append(Spacer(1, 40))

    content.append(
        Paragraph(
            "Recommendation: Production-Ready Deployment Path Identified",
            body_style,
        )
    )

    content.append(Spacer(1, 40))

    # =====================================================
    # BEFORE → AFTER WORKFLOW
    # =====================================================

    content.append(
        Paragraph(
            "Before → After Workflow Transformation",
            section_style,
        )
    )

    before = (
        data.get("workflowTransformation", {})
        .get("before", [])
    )

    after = (
        data.get("workflowTransformation", {})
        .get("after", [])
    )

    content.append(
        Paragraph(
            "<b>BEFORE — Manual Workflow</b>",
            body_style,
        )
    )

    for step in before:
        content.append(
            Paragraph(
                f"• {step}",
                body_style,
            )
        )

    content.append(Spacer(1, 12))

    content.append(
        Paragraph(
            "<b>AFTER — AI Native System</b>",
            body_style,
        )
    )

    for step in after:
        content.append(
            Paragraph(
                f"• {step}",
                body_style,
            )
        )

    content.append(Spacer(1, 24))

    # =====================================================
    # TIME REDUCTION SECTION
    # =====================================================

    content.append(
        Paragraph(
            "Operational Time Reduction",
            section_style,
        )
    )

    content.append(
        Paragraph(
            "Before: 45–60 minutes",
            body_style,
        )
    )

    content.append(
        Paragraph(
            "After: 10–15 minutes",
            body_style,
        )
    )

    content.append(
        Paragraph(
            "Estimated Efficiency Gain: ~75%",
            body_style,
        )
    )

    content.append(Spacer(1, 24))

    # =====================================================
    # AGENT DECISION SUMMARY
    # =====================================================

    content.append(
        Paragraph(
            "Agent Decision Summary",
            section_style,
        )
    )

    sections = [
        "architect",
        "critic",
        "refiner",
    ]

    for section in sections:
        block = data.get(section, {})

        title = block.get(
            "title",
            section.title(),
        )

        decisions = block.get(
            "decisions",
            [],
        )

        content.append(
            Paragraph(
                f"<b>{title}</b>",
                body_style,
            )
        )

        for item in decisions[:4]:
            content.append(
                Paragraph(
                    f"• {item}",
                    body_style,
                )
            )

        content.append(Spacer(1, 10))

    # =====================================================
    # ARCHITECTURE BLUEPRINT
    # =====================================================

    content.append(
        Paragraph(
            "Architecture Blueprint",
            section_style,
        )
    )

    layers = data.get(
        "architectureLayers",
        [],
    )

    for layer in layers:
        title = layer.get(
            "title",
            "Layer",
        )

        description = layer.get(
            "description",
            "",
        )

        content.append(
            Paragraph(
                f"<b>{title}</b>",
                body_style,
            )
        )

        if description:
            content.append(
                Paragraph(
                    description,
                    body_style,
                )
            )

        for item in layer.get(
            "items",
            [],
        )[:5]:
            content.append(
                Paragraph(
                    f"• {item}",
                    small_style,
                )
            )

        content.append(Spacer(1, 10))

    # =====================================================
    # FINAL METRICS
    # =====================================================

    content.append(
        Paragraph(
            "Final System Impact",
            section_style,
        )
    )

    for key, value in metrics.items():
        pretty_key = (
            key.replace("_", " ")
            .replace(
                "deploymentReadiness",
                "Deployment Readiness",
            )
            .replace(
                "automationPotential",
                "Automation Potential",
            )
            .replace(
                "architectureConfidence",
                "Architecture Confidence",
            )
            .title()
        )

        content.append(
            Paragraph(
                f"<b>{pretty_key}:</b> {value}",
                body_style,
            )
        )

    content.append(Spacer(1, 30))

    # =====================================================
    # FOOTER
    # =====================================================

    content.append(
        Paragraph(
            "Generated by SystemForge AI",
            small_style,
        )
    )

    content.append(
        Paragraph(
            "Production Architecture Intelligence Engine",
            small_style,
        )
    )

    doc.build(content)

    return filename